name: 'AKS Deployment & NGINX Deployment using Helm'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Azure
      uses: azure/login@v1.4.6
      with: 
         creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      working-directory: terraform
      run: terraform init
           
    - name: Terraform Format
      working-directory: terraform
      run: terraform fmt

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan 

    - name: Terraform Apply 
      working-directory: terraform
      run: terraform apply -auto-approve

    - name: Get Terraform Outputs
      id: terraform_outputs
      run: |
        export RESOURCE_GROUP="projectrsgrp"
        export AKS_CLUSTER="akscluster"
        echo "RESOURCE_GROUP=${RESOURCE_GROUP}"
        echo "AKS_CLUSTER=${AKS_CLUSTER}"
    
        # Use environment file to set outputs instead of set-output (deprecated)
        echo "RESOURCE_GROUP=${RESOURCE_GROUP}" >> $GITHUB_ENV
        echo "AKS_CLUSTER=${AKS_CLUSTER}" >> $GITHUB_ENV
        

  helm-deployment:
    name: 'NGINX Helm Deployment'
    runs-on: ubuntu-latest
    needs: terraform  # Ensure Terraform job completes before Helm deployment

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Authenticate to Azure
      uses: azure/login@v1.4.6
      with: 
         creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS Credentials
      run: |
          az aks get-credentials --resource-group projectrsgrp --name akscluster

    - name: Install Helm
      uses: azure/setup-helm@v1

    - name: Deploy Nginx using Helm
      run: |
          helm upgrade --install nginx-release ./nginx-test
